# Generated by Django 2.0.4 on 2018-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.CharField(blank=True, max_length=20, null=True)),
                ('species', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idprofile', models.PositiveIntegerField(db_column='idProfile', primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
