# Generated by Django 2.0.5 on 2018-07-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
