# Generated by Django 2.0.4 on 2018-11-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_group_groupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idplan', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plandetail',
            fields=[
                ('idplandetail', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plandetail',
                'managed': False,
            },
        ),
    ]
