# Generated by Django 2.0.4 on 2018-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_plan_plandetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('idchat', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=45, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.ImageField(max_length=30, upload_to='')),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
    ]
