# Generated by Django 2.0.5 on 2018-07-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('idnote', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('field', models.CharField(max_length=10)),
                ('subjects', models.CharField(max_length=10)),
                ('textbook', models.CharField(max_length=10)),
                ('intro', models.CharField(blank=True, max_length=45, null=True)),
                ('permission', models.IntegerField()),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteList',
            fields=[
                ('idnote_list', models.AutoField(primary_key=True, serialize=False)),
                ('list_text', models.CharField(blank=True, max_length=45, null=True)),
                ('list_num', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('noteid', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'note_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PollsDocument',
            fields=[
                ('iddoc', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'polls_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idnote', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
