# Generated by Django 2.0.5 on 2018-07-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
