# Generated by Django 2.0.4 on 2018-10-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'managed': False},
        ),
    ]
