# Generated by Django 2.0.4 on 2018-10-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20181010_0009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table='upload_favorite',
        ),
    ]
