# Generated by Django 2.1.3 on 2018-12-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20181010_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'upload_field',
                'managed': False,
            },
        ),
    ]
