# Generated by Django 2.1 on 2018-11-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20181010_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'managed': True},
        ),
    ]
